[package]
name = "weakauras_parser"
version = "0.1.0"
authors = ["Zireael <13710677+Zireael-N@users.noreply.github.com>"]
edition = "2018"
license = "MIT"

[dependencies]
inflate = "0.4.5"
lazy_static = "1.4.0"
regex = "1.3.4"
serde = { version = "1.0.104", optional = true }
